### ISSUE TITLE
Extremely incomplete database

### ISSUE THREAD

**Issue by AirikWarren** [cezarykluczynski/stapi#16]
I'm assuming that Memory Alpha or Memory Beta have changed something about their website in the last year, but for example, "The Cage" TOS episode only has 4 characters listed in this database.

**Comment by cezarykluczynski** [comment]
After a recent data update, [The Cage](http://stapi.co/api/v1/rest/episode?uid=EPMA0000000016) has now 12 performers and 12 characters listed. This is due to fact that a relation is maintained between performers and characters that have they own separate page. So, for example, [Felix Silla](https://memory-alpha.fandom.com/wiki/Felix_Silla) who played [3rd Talosian](https://memory-alpha.fandom.com/wiki/Talosian_observer_003), would not be listed. Whether this constraint should stay or go, is another question, of course.

**Comment by cezarykluczynski** [comment]
I gave it some thought and decided to break the link between performers and characters in episode and movies, as it wasn't exposed in the API anyway. So now [The Cage](https://stapi.co/api/v1/rest/episode?uid=EPMA0000000016&pretty) still has 12 characters, but 26 performers. Generally much more peformers are now linked from episodes and movies, and usually no new characters, but 1 or 2 more characters are present in around 1/4 of the cases,

I consider this particular issue resolved. If you are still interested in this subject, ad find more problems, please open a new issue describing them.
