### ISSUE TITLE
C# Client in net7.0

### ISSUE THREAD

**Issue by SteveWhitelaw2014** [cezarykluczynski/stapi#46]
First instance of a C# SDK client that can be accessed from Nuget.
Nuget page: https://www.nuget.org/packages/Meteorite.Stapi.Core/1.0.0

**Comment by cezarykluczynski** [comment]
@SteveWhitelaw2014 Thanks for your contribution and for letting everybody know. I will add it to the repository today, so it will be already visible in the README.md file, but it will take about 3 more weeks for this information to appear on stapi.co, due to monthly release cycle. Until then, I'll keep this issue open, if you don't mind.

**Comment by cezarykluczynski** [comment]
List of clients on the website has been updated as well.
